/**
 * GENZ-AI Tool Call & Action Parser
 * Robustly detects, extracts, and parses tool invocations from:
 * 1. Native API tool_calls arrays (Ollama & OpenAI)
 * 2. ReAct-style action JSON generated by models: {"action": "dalle.text2im", "action_input": "..."}
 * 3. Fenced markdown code blocks containing action JSON
 * 4. Text-based Action / Action Input declarations
 */

import { resolveTool, ToolDefinition } from "./registry";

export interface ParsedToolCall {
  tool: ToolDefinition;
  rawName: string;
  args: Record<string, unknown>;
  id?: string;
}

/**
 * Attempts to parse tool calls from a raw Ollama/OpenAI response message.
 */
export function parseToolCallFromResponse(message: {
  content?: string;
  tool_calls?: Array<{
    id?: string;
    function?: {
      name?: string;
      arguments?: Record<string, unknown> | string;
    };
  }>;
}): ParsedToolCall | null {
  // 1. Check native tool_calls first
  if (message.tool_calls && message.tool_calls.length > 0) {
    const firstCall = message.tool_calls[0];
    const rawName = firstCall.function?.name || "";
    const tool = resolveTool(rawName);

    if (tool) {
      let args: Record<string, unknown> = {};
      const rawArgs = firstCall.function?.arguments;
      if (typeof rawArgs === "object" && rawArgs !== null) {
        args = rawArgs as Record<string, unknown>;
      } else if (typeof rawArgs === "string") {
        try {
          args = JSON.parse(rawArgs);
        } catch {
          args = { input: rawArgs };
        }
      }
      return { tool, rawName, args, id: firstCall.id };
    }
  }

  // 2. Check message content for ReAct JSON or action strings
  const content = message.content?.trim();
  if (content) {
    return parseActionFromContent(content);
  }

  return null;
}

/**
 * Scans text content for ReAct action patterns and JSON tool invocations.
 */
export function parseActionFromContent(content: string): ParsedToolCall | null {
  if (!content) return null;
  const trimmed = content.trim();

  // A. Check for JSON code block: ```json { ... } ``` or ``` { ... } ```
  const codeBlockMatch = trimmed.match(/```(?:json)?\s*([\s\S]*?)\s*```/i);
  const textToScan = codeBlockMatch ? codeBlockMatch[1].trim() : trimmed;

  // B. Check if text contains a JSON object with "action", "tool", or "function"
  const jsonMatch = extractJsonObject(textToScan) || extractJsonObject(trimmed);
  if (jsonMatch) {
    try {
      const parsed = JSON.parse(jsonMatch);
      const actionName =
        parsed.action ||
        parsed.tool ||
        parsed.function ||
        parsed.name ||
        parsed.tool_name;

      if (typeof actionName === "string") {
        let tool = resolveTool(actionName);
        if (tool) {
          const args = {
            ...normalizeActionInput(parsed.action_input ?? parsed.parameters ?? parsed.arguments ?? parsed.args),
            ...(typeof parsed.prompt === "string" ? { prompt: parsed.prompt } : {}),
            ...(typeof parsed.query === "string" ? { query: parsed.query } : {}),
            ...(typeof parsed.text === "string" ? { text: parsed.text } : {}),
            ...(typeof parsed.expression === "string" ? { expression: parsed.expression } : {}),
            ...(typeof parsed.input === "string" ? { input: parsed.input } : {}),
          };

          // CRITICAL GUARD: Do NOT route video requests to image_generation or dalle.text2im
          const promptText = String(args.prompt || args.text || args.input || "");
          if (
            tool.name === "image_generation" &&
            /\b(?:video|clip|animation|mp4|5\s*second\s*video|short\s*video)\b/i.test(promptText)
          ) {
            tool = resolveTool("video_generation") || tool;
          }

          return { tool, rawName: actionName, args };
        }
      }
    } catch {
      // Continue to heuristics below
    }
  }

  // C. Check for ReAct text format:
  // Action: dalle.text2im
  // Action Input: {"prompt": "..."}
  const reactMatch = trimmed.match(
    /(?:Action|Tool):\s*([a-zA-Z0-9_.-]+)[\r\n]+(?:Action\s+Input|Inputs?):\s*([\s\S]+)/i
  );
  if (reactMatch) {
    const actionName = reactMatch[1].trim();
    let tool = resolveTool(actionName);
    if (tool) {
      const rawInput = reactMatch[2].trim();
      const args = normalizeActionInput(rawInput);

      const promptText = String(args.prompt || args.text || args.input || "");
      if (
        tool.name === "image_generation" &&
        /\b(?:video|clip|animation|mp4)\b/i.test(promptText)
      ) {
        tool = resolveTool("video_generation") || tool;
      }

      return { tool, rawName: actionName, args };
    }
  }

  // D. Lenient regex fallback for unescaped or malformed action JSON
  const actionRegexMatch = trimmed.match(/"(?:action|tool|function|name)"\s*:\s*"([^"]+)"/i);
  if (actionRegexMatch) {
    const actionName = actionRegexMatch[1].trim();
    let tool = resolveTool(actionName);
    if (tool) {
      const promptMatch = trimmed.match(/"(?:prompt|text|query|input|description)"\s*:\s*"([^"]+)"/i);
      const prompt = promptMatch ? promptMatch[1] : "";
      const args: Record<string, unknown> = {
        prompt,
        text: prompt,
        query: prompt,
        input: prompt,
      };

      if (
        tool.name === "image_generation" &&
        /\b(?:video|clip|animation|mp4)\b/i.test(prompt)
      ) {
        tool = resolveTool("video_generation") || tool;
      }

      return { tool, rawName: actionName, args };
    }
  }

  return null;
}

/**
 * Normalizes action_input which may be a raw string, an escaped JSON string, or a structured object.
 */
function normalizeActionInput(rawInput: unknown): Record<string, unknown> {
  if (!rawInput) return {};

  if (typeof rawInput === "object" && rawInput !== null) {
    return rawInput as Record<string, unknown>;
  }

  if (typeof rawInput === "string") {
    const trimmed = rawInput.trim();

    // 1. Try parsing directly as JSON
    try {
      const parsed = JSON.parse(trimmed);
      if (typeof parsed === "object" && parsed !== null) {
        return parsed as Record<string, unknown>;
      }
      return { input: parsed };
    } catch {
      // 2. Might be a wrapped/escaped JSON string
      const extractedJson = extractJsonObject(trimmed);
      if (extractedJson) {
        try {
          const parsed = JSON.parse(extractedJson);
          if (typeof parsed === "object" && parsed !== null) {
            return parsed as Record<string, unknown>;
          }
        } catch {
          // ignore
        }
      }

      // 3. Fallback: treat as raw prompt or input string
      return { prompt: trimmed, text: trimmed, query: trimmed, expression: trimmed, input: trimmed };
    }
  }

  return { input: String(rawInput) };
}

/**
 * Finds the best balanced outermost JSON object { ... } in a string.
 * Prioritizes objects containing action/tool/function keys.
 */
function extractJsonObject(str: string): string | null {
  if (!str) return null;

  const candidates: string[] = [];
  let startIdx = str.indexOf("{");

  while (startIdx !== -1) {
    let depth = 0;
    let inString = false;
    let escape = false;

    for (let i = startIdx; i < str.length; i++) {
      const char = str[i];

      if (escape) {
        escape = false;
        continue;
      }

      if (char === "\\") {
        escape = true;
        continue;
      }

      if (char === '"') {
        inString = !inString;
        continue;
      }

      if (!inString) {
        if (char === "{") {
          depth++;
        } else if (char === "}") {
          depth--;
          if (depth === 0) {
            const candidate = str.slice(startIdx, i + 1);
            candidates.push(candidate);
            break;
          }
        }
      }
    }

    startIdx = str.indexOf("{", startIdx + 1);
  }

  if (candidates.length === 0) return null;

  // Prioritize candidates that contain action, tool, or function
  const actionCandidate = candidates.find(
    (c) =>
      /"(?:action|tool|function|name)"/i.test(c) ||
      /"dalle/i.test(c) ||
      /"video/i.test(c) ||
      /"image/i.test(c)
  );

  return actionCandidate || candidates[0];
}
